### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kpraas** [TactileVision/TactJam-server#1]
### Features planned
- [x] Database scheme
- [x] Database-Server for handling
- [x] Node.JS server
- [x] Register
- [x] Login function
- [x] Logout / renew login function
- [x] automated API documentation
- [x] Password forgot functionality 
- [x] data managment functionality (copy, delete, update, insert), based on users
- [ ] overview page (i.e. showing stats etc, highly optional)

### Planned steps:
- [x] Ask at the HTW Dresden for an server which we can use (waiting for reply)
- [x] Create database scheme
- [x] Development of the Node.js Server
- [x] Install everything needed on the server
- [x] Setting up continuous integration (CI) on the server for easy updates
- [x] Develop and Test Server API
- [x] Test integration with the GUI Client
